---
title: "ggplot 1"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(ggridges)
```


Load a dataset that we'll use often

```{r, message = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## Scatterplot

tmax vs tmin
```{r,  message = FALSE}
ggp_tmax_tmin = 
  weather_df %>%
    ggplot(aes(x = tmin, y = tmax)) +
    geom_point()
```



#fancy the graph up

```{r, message = FALSE}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```


let's make one more scatterplot
```{r, message = FALSE}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, size = prcp)) + 
  geom_point(alpha = .3) + 
  facet_grid(. ~ name) + 
  geom_smooth(se = FALSE)
```


## use data manipulation as part of this
```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax_fahr = tmax * (9 / 5) + 32,
    tmin_fahr = tmin * (9 / 5) + 32
    ) %>% 
  ggplot(aes(x = date, y = tmax)) + 
  geom_point()
```


## Stcaking geoms


which geoms do you want

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```


hexagon plot
```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()

ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_bin_2d()
```


## Univariate plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_histogram() + 
  facet_grid(. ~ name)
```


try some other plots
```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density(alpha = .3)
```


still with tmax and tmin
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_boxplot()
```


Some people like violin plots
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin()
```


Bridges
```{r}
weather_df %>% 
  ggplot(aes(x = tmax, y = name)) + 
  geom_density_ridges(alpha = .8, scale = .8)
```


## Embedding plots
```{r, fig.width = 12}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5)
```



 
